PR for the initial web app
code-collabo/collabo-community-app pull request #1
Opened 2023-04-10 14:36 UTC by samuko-things

- #4 

@Ifycode this is the initial web-app.
Id like you to go through it and test it.

2023-04-10 15:25 UTC, Ifycode requested changes
Move all the new files and folders you have added into a folder called `client`.
(Create the `client` folder in the root of this repository).
@samuko-things

2023-04-11 10:53 UTC, samuko-things commented
I have moved all the frontend files and folders into the client folder as requested. please check it out

2023-04-17 00:53 UTC, Ifycode approved these changes

2023-04-17 00:53 UTC, Ifycode commented on client/.gitignore
> +# dependencies
I want to clean this up myself in a new PR, which I will merge into @samuko-things.
So I'll approve this PR so it'll let me merge into that branch.

2023-04-17 00:56 UTC, merged