added brief descriptive content in the readme
code-collabo/collabo-community-app pull request #24
Opened 2023-10-03 06:37 UTC by aybeedee

**This pull request makes the following changes**
* Fixes code-collabo/docs#35

**General checklist**
- [X] File or folder now contains changes as specified in the issue i worked on
- [X] I have linked the issue I worked on to this pull request submitted by me

**Testing checklist**

- [X] Simplified readme content added for Collabo Web App repo, following the footsteps of the example repos.
- [X] I certify that I ran my checklist

Ping @code-collabo/web-app

2023-10-03 23:16 UTC, Ifycode commented
**Review comment 1:** @aybeedee Awesome that you could link the issue fixed to the pull request. But help change your pull request title to "Fix: No content in readme". You can read more about this on the contributing guide page of our docs: https://code-collabo.gitbook.io/collabo-contributor/collabo-contributor-docs/contributing-guide

2023-10-03 23:23 UTC, Ifycode requested changes

2023-10-03 23:23 UTC, Ifycode commented on README.md
> +
**Review comment 2:** Badges nicely added. You can remove the issues badge for now. We have a different way of accessing issues according to our docs.

2023-10-03 23:23 UTC, Ifycode commented on README.md
> +<!-- ALL-CONTRIBUTORS-BADGE:END -->
**Review comment 3:** We have not set up @all-contributors bot for this repo, so you can remove the all contributors badge and comments for now. This part is addressed in another issue ticket.

2023-10-03 23:23 UTC, Ifycode commented on README.md
> +<!-- ALL-CONTRIBUTORS-LIST:END -->
**Review comment 4:** We have not set up @all-contributors bot for this repo, so you can remove the entire contributors section for now. This part is addressed in another issue ticket.

2023-10-04 01:17 UTC, aybeedee commented
Made all the required review changes. Also, I have a couple of questions. Why was the README from the "unreviewed" branch dropped? And also what is meant by "Ping @code-collabo/web-app"/how is it supposed to work (it's part of the PR Template).

2023-10-04 10:14 UTC, Ifycode commented
Good question @aybeedee 
We are centralizing our docs so that we don't have to repeat information. You can take a look at the contributing doc for the Collabo web app to see: https://code-collabo.gitbook.io/collabo-contributor/collabo-web-app-project/contribute-to-collabo-web-app
So now, we just send people to the docs from the readme for all the info they need.
#
Just ignore the ping part of the PR template for now. It may just be one of the clean ups we will do.

2023-10-04 10:15 UTC, Ifycode approved these changes
Neatly done @aybeedee

2023-10-04 11:22 UTC, merged