FIX: Convert the style guide from figma design into base styles
code-collabo/collabo-community-app pull request #47
Opened 2023-10-27 22:04 UTC by samuko-things

**This pull request makes the following changes**
* Fixes code-collabo/collabo-community-app#40 

**General checklist**
- [x] File or folder now contains changes as specified in the issue i worked on
- [x] I have linked the issue I worked on to this pull request submitted by me

**Testing checklist**

- [x] Convert the style guide from our figma design into base styles:
- Colors
- Typography
- Fonts

Ping @code-collabo/web-app

2023-10-27 22:08 UTC, samuko-things commented
@Ifycode @Festusali @Geefundesign

I have added the base color and typography style guide from the community app Figma design as variables in the var.css file as instructed. I currently remain the underline part. I have also tested them externally.

please do check it out and let me know what you think.

2023-10-31 05:10 UTC, Ifycode commented
Just tag @code-collabo/community-mentors next time.
Reviewing your PR...

2023-11-01 06:06 UTC, Ifycode requested changes

2023-11-01 06:06 UTC, Ifycode commented on client/src/styles/base/var.css
> +  --typo-semi-bold-h3: 600 24px/32.68px 'Open Sans';
**_Review comment 1:_**
Nice work so far @samuko-things 
Help change `--typo` to `--type` everywhere it is used.

2023-11-01 06:06 UTC, Ifycode commented on client/src/styles/base/var.css
> +  /* https://www.w3schools.com/cssref/pr_font_font.php */
**_Review comment 2:_**
Interesting. This is my first time seeing font size and line height written in this manner. The link is helpful @samuko-things 

What about if the owners of that reference site changes their link or it become none existent?

You can just help add a comment below the reference link that gives an idea of the format ou used e.g
````
/* --type-style-format: font-weight font-size/line-height font-family */
````

2023-11-01 10:10 UTC, samuko-things commented on client/src/styles/base/var.css
> +  --typo-semi-bold-h3: 600 24px/32.68px 'Open Sans';
ok

2023-11-01 10:11 UTC, samuko-things commented on client/src/styles/base/var.css
> +  /* https://www.w3schools.com/cssref/pr_font_font.php */
ok will do

2023-11-01 10:12 UTC, samuko-things commented
> Just tag @code-collabo/community-mentors next time. Reviewing your PR...

ok noted.

2023-11-01 11:53 UTC, samuko-things commented
I have just added a style guide for the underline functionality based on the figma design to be used with text-decoration property. I've also tested it. please do check it out and let me know what you think.

2023-11-01 13:43 UTC, Ifycode approved these changes
Awesome work @samuko-things
Approved.

2023-11-01 13:43 UTC, merged